# Generated by Django 4.0.6 on 2022-09-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=0)),
                ('lat_1', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
                ('lat_2', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
                ('long_1', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
                ('long_2', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
                ('altitude', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.IntegerField(default=0)),
                ('class_location_x', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
                ('class_location_y', models.DecimalField(decimal_places=200, default=0.0, max_digits=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Physics', models.IntegerField(default=0)),
                ('Chemistry', models.IntegerField(default=0)),
                ('Maths', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_record', to='attendance_marker.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_string', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('time_of_lecture', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_of_student', to='attendance_marker.student')),
            ],
        ),
    ]
